export const ROUTES = {
  HOME: "/",
  REGISTER: "/register",
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgotPassword",
  ENTER_OTP: "/enterOtp",
  CHANGE_PASSWORD: "/changePassword",
  NOTIFICATIONS: "/notifications",
  CHATBOT: "/chatbot",
  BLOG: "/blog",
  BLOG_POST: "/blog-post/:id",
  // PROFILE: '/profile',
  FACE_DETECTION: "/face-detection",
  CHATBOT_LANDING_PAGE: "/chatbot-landing-page",
  MAIN_PAGE: "/suggestions",
};
