export const ROUTES = {
  HOME: "/",
  REGISTER: "/register",
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",
  ENTER_OTP: "/enter-otp",
  CHANGE_PASSWORD: "/change-password",
  NOTIFICATIONS: "/notifications",
  CHATBOT: "/chatbot",
  BLOG: "/blog",
  BLOG_POST: "/blog-post/:id",
  // PROFILE: '/profile',
  FACE_DETECTION: "/face-detection",
  CHATBOT_LANDING_PAGE: "/chatbot-landing-page",
};
